CI/CD updates: split integration and linting, integrated running example from built project
dos-group/vessim pull request #128
Opened 2023-08-28 12:13 UTC by amandamalk0601

Seperated integration and linting tasks into two pipelines.
CI pipeline:
- Runs on every pull request
- Uses Poetry to build and install a package from the latest main branch code.
- Tests the installed package by running the example scenario cosim_example.py, verifying file paths are set correctly.
- Executes pytests

Linting-and-type-checking pipeline:
- Runs on every commit
- Runs mypy and ruff

Fixed paths in ``_data.py``, ``cosim_example.py``, and ``cosim_sil_example.py``, by changing every occurrence of  ``from example._data import`` to ``from _data import``. ``example`` is no module or package, so it should not be used as one. 
Now, ``cosim_example.py`` can be run successfully after installing the Poetry-built 'vessim' package using ``python cosim_example.py``.

Modified ``pyproject.toml`` to include dynamic versioning with a Poetry version [plugin](https://pypi.org/project/poetry-version-plugin/). The version number is specified to be extracted from a git tag.

2023-08-28 14:32 UTC, birnbaum requested changes
Nice! Two last changes:
- The unit tests (so currently all tests we have) should also run on every commit, the old name "linting-and-testing" was fine!
- the second pipeline is really just for building the package and running the example. As a last step in this pipeline we could compare the resulting data.csv with one that we put in the repo to ensure that the results are the same :)

2023-08-29 12:51 UTC, amandamalk0601 commented
Now I included the comparison between the resulting data.csv and the one present in the repo.
Currently the resulting data.csv differs from the present one, this is why the ci pipeline fails. 
And I moved the tests to the linting-and-tesing pipeline.

2023-08-31 11:06 UTC, kilianp14 commented on .github/workflows/ci.yml
> +        python $GITHUB_WORKSPACE/examples/cosim_example.py > $GITHUB_WORKSPACE/testing_results/data.csv
I think that the folder structure will change quite a bit because of the new big PR. So we should probably wait till thats merged and update it then.

2023-08-31 17:36 UTC, amandamalk0601 commented on .github/workflows/ci.yml
> +        python $GITHUB_WORKSPACE/examples/cosim_example.py > $GITHUB_WORKSPACE/testing_results/data.csv
Alright :)

2023-09-08 12:59 UTC, marvin-steinke approved these changes

2023-09-17 16:08 UTC, birnbaum approved these changes

2023-09-17 16:08 UTC, merged