Trace forecasts
dos-group/vessim pull request #138
Opened 2023-09-22 13:20 UTC by kilianp14

- A bit of restructuring of core.simulator so that some functionality is abstracted from CarbonApi
- Integration of a forecast_at function to get forecasts: A frequency and a resample_method can be specified and data will be interpolated accordingly (detailed information about the functionality can be found in the docstring). Tests for this function are implemented too
- Auto-formatting of the test files
- Implementation of apply_error function for the datasets (some changes need to be made though #142)

2023-09-23 09:16 UTC, marvin-steinke commented on vessim/core/simulator.py
> +            ------------------------------------------------------------------------
why are the forecasts formatted differently than the actual data?

2023-09-23 09:35 UTC, marvin-steinke requested changes
Looking good!

2023-09-23 09:35 UTC, marvin-steinke commented on vessim/core/simulator.py
> +            return zone_forecast.loc[self.data.index.asof(dt)]
```suggestion
            return zone_forecast.loc[self.actual.index.asof(dt)]
```

2023-09-23 09:35 UTC, marvin-steinke commented on vessim/core/simulator.py
> +        return self.actual.index[next_iloc]
Are out of bounds exceptions an issue here?

2023-09-23 09:35 UTC, marvin-steinke commented on vessim/core/simulator.py
>      def carbon_intensity_at(self, dt: Time, zone: Optional[str] = None) -> float:
Do we even need this and the `power_at` function anymore?

2023-09-23 11:31 UTC, kilianp14 commented on vessim/core/simulator.py
> +            ------------------------------------------------------------------------
Because the forecast has two relevant timestamps, one for the time that the forecast is made and one for the time the forecast is for. The format itself is not yet fixed, and I would suggest discussing it.

2023-09-23 11:33 UTC, kilianp14 commented on vessim/core/simulator.py
> +        return self.actual.index[next_iloc]
Could be. I did not write this function though

2023-09-23 11:36 UTC, kilianp14 commented on vessim/core/simulator.py
> +            return zone_forecast.loc[self.data.index.asof(dt)]
It is just a draft of this function at the moment. I dont think we can actually write it yet without knowing anything about what format the forecasts should have.

2023-09-23 11:40 UTC, kilianp14 commented on vessim/core/simulator.py
>      def carbon_intensity_at(self, dt: Time, zone: Optional[str] = None) -> float:
Not really. But in my opinion, it would be sensible to have another Base Class for the Generator and the CarbonApi later for when we want to integrate real-time data and these functions could be good abstract methods. So, I just left them.

2023-10-13 08:29 UTC, birnbaum approved these changes

2023-10-13 08:29 UTC, birnbaum commented on vessim/core/simulator.py
> +        return self.actual.index[next_iloc]
that's ok for now, if this throws an IndexError it's job of the simulator to handle that

2023-10-13 08:29 UTC, merged